### ISSUE TITLE
Check directory structure. Folder and files copy.

### ISSUE THREAD

**Issue by gurdev7** [chandkc/MIST#18]

**Comment by gurdev7** [comment]
Common folder for all mistdata, all cif pot, all gas pot.

**Comment by bishweshwarShome** [comment]
suggested folders name:

cif_mistdata: all mistdata files of structures (cif)
cif_pot: all pot files of structures (cif)
gas_pot: selected adsorbate pot files

**Comment by gurdev7** [comment]
Do it on the server side
